name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run coverage
      - run: npm run build
      - run: npm run publish-copy
      - run: npm publish ./dist/src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload package
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: ./dist/src
          fail_ci_if_error: true
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Premiss ${{ github.ref }}
          draft: false
          prerelease: false