name: test

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run coverage
      - run: npm run example
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/premiss/coverage-final.json
          flags: premiss
          name: codecov-umbrella
          fail_ci_if_error: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/example/coverage-final.json
          flags: example
          name: codecov-umbrella
          fail_ci_if_error: true